#!/bin/bash

mountpoint=${1:-/tmp/lomount}
dev=$(mount | grep $mountpoint | awk '{ print $1 }')
if [ -z "$dev" ]; then
  echo Nothing to do for $mountpoint > /dev/stderr
  exit 1
fi
umount $mountpoint
losetup -d $dev