#!/usr/bin/env bash

user=$1
encrypted_password='$6$AnsGo.oCkarlHTL$Gx4MoVpjgf81LB/.ps/UxPyrRZOz/UAsXV0UvN5Bhif88EFAgeagq0cRk5PKt763gR8VYLjb3ToaWju8PIyg20'

if grep -q $user /etc/passwd; then
  echo already created
  exit
fi

echo $user not found, creating...

useradd -m -p $encrypted_password -s /bin/bash $user
usermod -aG sudo $user
chown -R $user:$user /home/$user

sshdir="$(su $user -c 'echo $HOME')/.ssh"

su $user << EOF
mkdir -p $sshdir
curl -Ls https://github.com/$user.keys -o $sshdir/authorized_keys
EOF


