#!/usr/bin/env bash

SHORT="ur"
LONG=install,remove,help
OPTS=$(getopt -a -n pkg --options $SHORT --longoptions $LONG -- "$@")

VALID_ARGUMENTS=$# # Returns the count of arguments that are in short or long options

if [ "$VALID_ARGUMENTS" -eq 0 ]; then
  help
fi

eval set -- "$OPTS"
help() {
  echo "Usage: $(basename $0) [-iu] packages" 1>&2
}

while :
do
  case "$1" in
    -i | --install )
      cmd=install
      shift 1
      ;;
    -r | --remove )
      cmd=remove
      shift 1
      ;;
    -h | --help)
      help
      exit 0
      ;;
    --)
      shift;
      break
      ;;
    *)
      break
      ;;
  esac
done
if [ -z "$cmd" ]; then
  help
  exit 1
fi

if [ $cmd == install ]; then
  sudo pacman -S --noconfirm $@
elif [ $cmd == u ]; then
  sudo pacman -R --noconfirm $@
fi
