#!/bin/bash
usage() {
  remote_run HOST PATH/TO/SCRIPT
}

err_exit() {
  echo "$@" 1>&2
  exit 1
}

host=$1
shift 1
while [ "$1" != "--" ] && [ -n "$1" ]; do
  scripts="$scripts $1"
  shift 1
done

[ -n "$host" ] || err_exit host is required
[ -n "$scripts" ] || err_exit script is required

for script in $scripts; do 
  if [ ! -f "$script" ]; then
    echo script does not exist
    exit 1
  fi
done

ssh -t $host "$(cat $scripts)";
