#!/usr/bin/env bash

set -x

kernel=$(uname -s | tr '[:upper:]' '[:lower:]')

if grep -q 'NAME=NixOS' /etc/os-release; then
  name=${1:-$(hostname)}
  git add . -A
  sudo nixos-rebuild switch --flake ".#$name"
  exit
else
  name=${2:-$(hostname)}
fi

do_bld() {
  nix --extra-experimental-features "nix-command flakes" build "$1"
}

build() {
  git add . -A
  if [ "$kernel" == darwin ]; then
    do_bld .#darwinConfigurations.$name.system
  elif [ "$kernel" == linux ]; then
    do_bld .#homeConfigurations.user.activationPackage
  fi
}

home() {
  ./result/activate-user
}

system() {
  ./result/activate
}

case $1 in
  "home")
    build && home;;
  "system")
    build && system;;
  "sys")
    build && system;;
  "both")
    build && home && system;;
  "")
    build && home && system;;
  *)
    echo "expected 'home' or 'sys[tem]'";;
esac
