#!/bin/bash

REPO=${1}
if [ -z $REPO ]; then
  echo repo argument is required > /dev/stderr
  exit 1
fi
curl -s \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/repos/$REPO/releases/latest | jq -r '.tag_name'
