#!/usr/bin/env bash
msg=$1

if [ -z "$msg" ]; then
  echo message required > /dev/stderr
  exit 1
fi

if [ ! -f .git ] && [ ! -d .git ]; then
  echo "You are not in a git repository" > /dev/stderr
  exit 1
fi

git add . -A
git commit -m "$msg"
git push
