version: "2.1"
volumes:
  src:
  pkgs:
services:
  dev:
    build: .
    network_mode: host
    privileged: true
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
      io.balena.features.journal-logs: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    volumes:
      - 'src:/home/zwhitchcox/src'
      - 'pkgs:/nix'
