#!/usr/bin/env bash
commands=(
  calendar
  mail
)
users=(
  zwhitchcox
  balena
)

maybe_start_firefox() {
  if ! wmctrl -l | grep -iq firefox ; then
    nohup firefox $@ &>/dev/null &
    sleep 2
  else
    firefox $@
  fi
}

calendar() {
  clear
  local user=$(get_selection -n "${users[@]}")
  maybe_start_firefox "https://calendar.google.com/calendar/u/$user/r"
  local winid=$(wmctrl -l | grep -i firefox | tail -n 1 | awk '{print $1}')
  sleep 1
  #wmctrl -r $winid -t 2
}

mail() {
  clear
  local user=$(get_selection -n "${users[@]}")
  maybe_start_firefox "https://mail.google.com/mail/u/$user/#inbox"
  sleep 1
}

clear
eval $(get_selection "${commands[@]}" )
