#!/usr/bin/env bash

pd=$(project_dir)
cd $pd
filter_exists() {
  local in;
  while read in; do
    test -d "$pd/${in##*/}" || echo "$in"
  done
}

if [ -n "$1" ]; then
  selection=$(remote_projects | filter_exists | tac | fzf)
else
  selection=$1
fi
git clone --recurse-submodules git@github.com:$selection
dev ${selection##/*}
