#!/bin/bash
eexist() {
  echo "$1" already exists
  exit 17
}

project_path=$1

# if remote_projects | grep -i ${project_name##*/} ; then
#   if getyn $project_name already exists. Clone it? ; then
#     git clone 
#   fi
# fi

# create and cd to project path
echo "initializing $project_path"
test -d "$project_path" && eexist "$project_name"
mkdir -p "$project_path" && cd "$project_path"
git init
