#!/usr/bin/env bash

strip_SRCDIR() {
  local my_path=$(realpath $1)
  [[ $my_path/* == $SRCDIR/* ]] && echo ${my_path:$((${#SRCDIR}+1))} && return 0
  return 1
}

# output all projects in order of most recently used
relpath() {
  local p1=$1
  local p2=$2
  echo $(dirname ${p2:$((${#p1}+1))})
}

output_all() {
  local projects=$(find -L $SRCDIR/$ENV -type d -name '.git')
  for project in $projects; do
    strip_SRCDIR $project
  done
}


filter_deleted() {
  local in;
  while read in; do
    test -r "$SRCDIR/$in/.git" && [ -n "$in" ] && echo "$in"
  done
}

touch $DEVHIST

cat <(tac $DEVHIST) <(output_all) | awk '!x[$0]++' | sed 's/^/  /' | head -n 10 | filter_deleted
