#!/usr/bin/env bash
config_file="$(project_dir)/.config"

if [ ! -f "$config_file" ]; then
  echo $config_file does not exist 1>&2
  exit 1
fi

source $config_file

if [ -z "$ORGS" ]; then
  echo No ORGS found in $config_file 1>&2
  exit 1
fi

output_repos() {
  for org in $(echo $ORGS | sed 's/,/\n/g'); do 
    gh repo list --limit 100 --json pushedAt,nameWithOwner $org &
  done
}

resp="$(output_repos)"

wait

echo "$resp" | jq -s 'flatten(1)' | jq -r '.|=sort_by(.pushedAt)' | jq -r '.[].nameWithOwner' # | jq -r '.[] | (.pushedAt | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%Y-%m-%d")) + " " + (.nameWithOwner)'
