#!/bin/bash

status_all() {
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  NC='\033[0m' # No Color
  for proj in $(recent_projects); do
    cd $SRCDIR/$proj
    local s="$(git status -s)"
    if [ -n "$s" ]; then
      echo -e "$proj" # ${RED} x${NC}"
      git status -s
    # else
    #   echo -e "$proj ${GREEN} ✓${NC}"
    fi
  done
}


status_one() {
  local proj_path=$SRCDIR/$ENV/$1
  if test -d $1; then
    cd $1
  elif test -d $proj_path; then
    cd $proj_path
  else
    echo $1 not found >/dev/stderr
    exit 1
  fi
  for f in $(git ls-files --others --exclude-standard -z); do
    git add -N $f
  done
  git diff
}

if [ -z $1 ]; then
  status_all
else
  status_one $@
fi
